version: "3.3"
services:
  db:
    image: "postgres:latest"
    restart: always
    ports:
      - "9000:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: emre
      POSTGRES_PASSWORD: test
      POSTGRES_DB: ambisocial
  aspnet:
    build: .
    depends_on:
      - db
    ports:
      - "5000:80"
    restart: always
volumes:
  postgres_data: